# Copyright 2019-2022 DADoES, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License in the root directory in the "LICENSE" file or at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#The package.yml file contains the location of models to be loaded from Blender files.
#The name of the objects map to the name of a collection in the blender file.

# This package uses bundled package data. The data is located in the package itself under
# a sub directory defined by the 'example' logical name.
# The logical name is then used in the "objects" block to refer to that location.
# For instance, "example:LowPoly.blend" refers to "data/LowPoly.blend" in the example
# package directory
volumes:
  example: 'df8ad806-223b-4d56-a932-838da835ec62'

# Define objects.
objects:

  YoYo:
    filename: example:LowPoly.blend

  BubbleBottle:
    filename: example:LowPoly.blend

  Skateboard:
    filename: example:LowPoly.blend

  Cube:
    filename: example:LowPoly.blend

  Mix Cube:
    filename: example:LowPoly.blend

  PlayDough:
    filename: example:LowPoly.blend

  Light Wooden Box:
    filename: example:containers.blend

  Dark Wooden Box:
    filename: example:containers.blend

  Blue Tub:
    filename: example:containers.blend

  Orange Tub:
    filename: example:containers.blend

  Green Tub:
    filename: example:containers.blend

  Clear Tub:
    filename: example:containers.blend

  Gray Tub:
    filename: example:containers.blend

  Yellow Bowl:
    filename: example:containers.blend

  Purple Bowl:
    filename: example:containers.blend

  Short Basket:
    filename: example:containers.blend

  Tall Basket:
    filename: example:containers.blend

  Plane Floor:
    filename: example:floors.blend

  Tile:
    filename: example:floors.blend

  Cobbles:
    filename: example:floors.blend

  Wood:
    filename: example:floors.blend

  Rocks:
    filename: example:floors.blend

  Granite:
    filename: example:floors.blend

  Metal:
    filename: example:floors.blend